@startuml
前端 -> 结算: fetchInfo
结算 -> 缓存: 1.查询流程配置信息
缓存 -> 数据库: 2.查询流程配置
数据库 --> 缓存 : return
缓存 -> 缓存 : 3.存储
缓存 --> 结算 : return
结算 -> 结算 : 4.取模块配置、校验必传参数
结算 -> 结算 : 5.灰度配置处理
结算 -> 结算 : 6.根据info/submit流程\n对应模块配置反射调用具体类
结算 --> 前端: return
@enduml